### ISSUE TITLE
Claymore's Ethereum miner support

### ISSUE THREAD

**Issue by GitHubGiggity** [Vetal-inside/FCl#1]
I was able to pull all of claymore's eth address from the log files (I believe claymore uses 8 eth addresses for his dev fee), hope this helps you in making it compatible with claymore eth miner.

0x3509F7bd9557F8a9b793759b3E3bfA2Cd505ae31
0xdE088812A9c5005b0dC8447B37193c9e8b67a1fF
0xe19fFB70E148A76d26698036A9fFD22057967D1b
0x7Fb21ac4Cd75d9De3E1c5D11D87bB904c01880fc
0x34FAAa028162C4d4E92DB6abfA236A8E90fF2FC3
0xc6F31A79526c641de4E432CB22a88BB577A67eaC
0xB9cF2dA90Bdff1BC014720Cc84F5Ab99d7974EbA
0xc1c427cD8E6B7Ee3b5F30c2e1D3f3c5536EC16f5

Also, was looking at your code and I am fairly new and was wondering if it was possible to use a regex to replace strings instead of StringReplace. That way, you can have it look for specific dev fee addresses in the future or if it changes, automatically.

For example: Here is a login line from your program when I log it using claymore's eth mining:
19:21:40:702	cfc	send: {"worker": "eth1.0", "jsonrpc": "2.0", "params": ["0xB9cF2dA90Bdff1BC014720Cc84F5Ab99d7974EbA", "x"], "id": 2, "method": "eth_submitLogin"}

So wouldn't a regex of:
("0x)([a-zA-Z0-9]{40})(", "x")
return a match so you can replace it with your own address? I found out that the only time it sends "x" is when it is sending in login details. So once it matches, you can have it replace your own line:
"0xNewAddress", "x"

I was testing the regex at https://regex101.com/ but don't know how to implement it in your program/C++. Was trying to figure out how to make it more dynamic.

**Comment by Vetal-inside** [comment]
Hi GitHubGiggity!

At first - thanks for your effort and collected eth addresses, it is pleasure that someone want help.

You are right - SringReplace is the simplest, but so stupidly and no effective method, to replace dev fee address. I thought about replacing dev fee address through JSON(that's 100% guaranteed method, but not much effective), but your idea with regex looks more better.

About compatibility with eth miner - at now I working on compatible with dev fee via SSL(already done, but need some tests) and more easily configuring network connection. And after, next goal - adding supporting Claymore's Ethminer.

**Comment by GitHubGiggity** [comment]
Your welcome. The only problem I have is I am not sure what command it is to use regex for replacements. The regex tester site at https://regex101.com/ uses PCRE and is not sure how to implement that into C++. If you can help, I can surely create a regex match for zcash and monero and any other ones out there. I mostly mine ETH, which was why I was trying to figure out a regex match with ETH first, because claymore can easily update his ETH addresses in future versions. That way, your program will still work. I tested that regex on 48 hours worth of logs across 4 rigs at https://regex101.com/, and it matched only the dev fee correctly every time. I just need to figure how the "if regex matches, then replace with..." command. Any help/idea would be appreciated. I'm pretty stumped and new.

**Comment by Vetal-inside** [comment]
I thought about it yesterday, and decided that retrieving and replacing login via json looks better, that regex. May be not same effective (from performance side), but gives 100% warranty for success, because login not always is wallet - sometimes it <login.worker> pair ("claymore.fee" for suprnova, as example).

Finally - I think, that as default algo there will be replacing through json, but if user sure that login is always wallet, he may choose regex option in settings.
Something like this...

**Comment by GitHubGiggity** [comment]
If that is the case, then here is a universal regex, that should work if there is a worker name pair or not, as you mention from your example (claymore.fee). The following should also work if it's a normal payment address. 

(")([a-zA-Z0-9._-]{2,80})(", "x")

I tested the above at https://regex101.com/ and it also provided 100% match success rate. Hope this helps.

**Comment by Vetal-inside** [comment]
I just uploaded all my commits for last week and make new release. Current version(v0.1.1) support Claymore's ethminer 7.4 (but with some limitations). So I close this issue.
