### ISSUE TITLE
Auto start on load?

### ISSUE THREAD

**Issue by GitHubGiggity** [Vetal-inside/FCl#2]
Ran into an issue. My rigs crashed due to a black out and the rigs couldn't connect because with your program, you need to physically click on "Listen" for the proxy to start working. How would you make it automatically listen when the program loads if I add it to the start up folders?

**Comment by Vetal-inside** [comment]
You are right. I will add possibility to save current settings into config file and autostart feature(button click event will occur without user ) in nearest future.
At hotfix now - you can add failover pool, which is not present in in changed hosts file. I think this must work.

**Comment by Vetal-inside** [comment]
Added in current release (v0.1.1) too: you can set your personal setting in config.txt file (including the auto startup option).
