### ISSUE TITLE
Optiminer Support

### ISSUE THREAD

**Issue by dlehenky** [Vetal-inside/FCl#4]
Claymore doesn't even have the best Zcash miner, at this point. Optiminer is the best performing ZEC miner, for now. Why just target Claymore?

**Comment by Vetal-inside** [comment]
I had plans about optiminer. But at current stage there are need totally rework FCl "core". And it need lot of time. So...I have not any terms for adding optiminer support "from box".

**Comment by Vetal-inside** [comment]
Anyone use optiminer now? Looks like newest claymore's zcash miner is faster, so issue was solved by definition.
